using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;

namespace BasicChannelFactory
{
    // This code generated by svcutil.exe.
    [ServiceContract()]
    public interface IOneWayCalculator
    {
        //[OperationContract()]
        //double Add(double A, double B);
        [OperationContract]
        double Add(double n1, double n2);
        //[OperationContract(IsOneWay = true)]
        //void Subtract(double n1, double n2);
        //[OperationContract(IsOneWay = true)]
        //void Multiply(double n1, double n2);
        //[OperationContract(IsOneWay = true)]
        //void Divide(double n1, double n2);
        //[OperationContract]
        //string SayHello(string name);
    }

    class Program
    {
        static void Main(string[] args)
        {
            OneWayCalculatorClient client = new OneWayCalculatorClient();

            // Use the 'client' variable to call operations on the service.

            // Always close the client.
            client.Close();
        }
    }
}
